name: app
description: A Flutter application that integrates with Google Vertex AI/Discovery Search

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Google API libraries for Dart (contains Vertex AI, Discovery Engine, Retail, etc.)
  googleapis: ^12.0.0
  
  # Authentication library for obtaining OAuth2 or service-account credentials in Dart
  googleapis_auth: ^1.4.0
  
  # Often helpful for custom requests, if needed
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
